### ISSUE TITLE
[45] Connections, services and integrations monitor

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#207]
Allows admin role to check statuses and details of some connections, services and integrations like:

- [x] DB connection (details should be presented) (#201);
- [x] E-mail server connection (details should be presented) - exsisting functionality (#209);
- [x] Internet connection- exsisting functionality (#209);
- [x] API services (details should be presented) (#208).

Mockup screen:
![image](https://user-images.githubusercontent.com/26207880/89015129-dc7ad480-d316-11ea-98e6-117e70738050.png)

**Comment by JaRutkowski** [comment]
@MatSzymczyk - PFA.
