### ISSUE TITLE
[40] Rewrite the persistance layer

### ISSUE THREAD

**Issue by JaRutkowski** [JaRutkowski/eLibrary#321]
# Concept

- Engine (JDBC/JPA/Hibernate/another),
- Architecture (Local/Remote Server),
- Performance tests (manual/JMetter).

# High-level process

1. Decompose domain,
2. Write new persistance layer,
3. Rewrite all dependent places in elibrary-core,
4. Perform performance tests,
5. Deploy change.

# Architecture&technology

![elibrary-architecture-v5 0 drawio](https://user-images.githubusercontent.com/108392258/206929189-0b5d8419-f6f3-460f-83be-1cc974e56e68.png)

# Development

- [x] #352
- [ ] #351
- [ ] #353
- [ ] elibrary-user-data-micro
- [ ] elibrary-lend-micro
- [ ] elibrary-dictionary-micro
- [ ] elibrary-email-micro
- [ ] elibrary-settings-micro

**Comment by JaRutkowski** [comment]
Use Hibernate 6 and upgrade PostgreSQL (including Driver).
In Hibernate 6 jakarta is used instead of the javax.persistaence.
